# sentences 문장 중 임의의 문장을 출제 후 사용자가 타이핑하는 시간(종료시간-시작시간)을 잰 후 저장
# 정확도 계산 : 문자단위로 비교
# 데이터 베이스에 저장할 것 : 시도횟수(번호 자동증가), 걸린시간, 정확도, 날짜

import random
import oracledb
import time

sentences = [
    "The quick brown fox jumps over the lazy dog",
    "Python is a powerful programming language",
    "Practice makes perfect every single day",
    "Oracle database stores data reliably",
    "Typing speed improves with daily practice",
]

conn = oracledb.connect(
    user="python_user",
    password="54321",
    dsn="localhost/xe"
)
cursor = conn.cursor()

try : 
    #테이블 생성 : typing_records()
    sql = """create table typing_records(
    record_id number(10) GENERATED BY DEFAULT AS IDENTITY primary key, 
    elapsed varchar2(20) not null,
    accuracy varchar2(20) not null
    )
    """  
    cursor.execute(sql)    


except oracledb.DatabaseError as e:    
    (error_obj,) = e.args
    if error_obj.code == 955:
        print(error_obj.message)        
    else:
        raise
# 문제출제 (임의 문장하나 선택)

    """문장 중 하나를 무작위로 선택해서 반환"""

target = random.choice(sentences)
# target random.sample(sentences,k=1)

print("아래 문장을 그대로 입력하세요:")
print(target)
input("준비되면 Enter를 누르세요...")

# 시간
start = time.time()
typed = input()
end = time.time()
# 걸린 시간
elapsed = format(end - start,".3f")

# 정확도 계산
# zip() : 동일 개수로 이루어진 data들을 묶어서 반환해주는 함수, 길이가 다르면 짧은 쪽 기준 
# print(list(zip([1,2,3],[4,5,6])))  => [(1, 4), (2, 5), (3, 6)]
# print(list(zip([1,2,3],[4,5,6],[7,8,9]))) => [(1, 4, 7), (2, 5, 8), (3, 6, 9)]
# print(list(zip("abc","def"))) => [('a', 'd'), ('b', 'e'), ('c', 'f')]

correct_chars=0
for a, b in zip(target,typed):
    if a== b:
        correct_chars +=1

# 위에 것을 패션코드로 만들면
#  correct_chars = sum(1 for a,b in zip(target,typed) if a == b )  

# 정확도
accuracy = correct_chars / len(target)  * 100
accuracy = format(accuracy, ".1f")

# 삽입
sql = "insert into typing_records(elapsed,accuracy) values(:1,:2)"
cursor.execute(sql,(elapsed,accuracy))
conn.commit()

cursor.close()
conn.close()



