# 영어타자 프로그램
import time
import random

# word.txt 읽어서
words = []
with open("./word.txt","r",encoding="utf-8") as f:  #모듈은 가상환경(.venv)에서 가동되서 ch1폴더를 지정해줘야함. 현재 경로는 C:\source\pythonsource> .ipynb확장자는 자동으로 찾아주는데 .py는 아니라서 폴더 상세하게 지정
    for word in f:
        words.append(word.strip())  # strip : 공백/엔터 제거

# print(words)
start = time.time()

# n : 반복횟수 카운트, corr_cnt : 정답 개수 카운트
n, corr_cnt = 1, 0

while n <= 5:
    # 섞는다 random.shuffle()
    random.shuffle(words)
    # 임의로 하나 추출 random.choice()
    q = random.choice(words)
    # 문제 5문제 출제
    # 정답 개수
    # Q1) then
    print(f"Q{n}")
    print(q)
    # input()
    answer = input()
    # input 결과에 따라 정답!! or 오타!!
    if answer.strip() == q.strip():
        print("정답!!")
        corr_cnt += 1
    else:
        print("오타!!")

    # 문제 개수 추가
    n += 1

# 끝난시간
end = time.time()

# 게임시간 출력
et = end - start
et = format(et, ".3f")

# 출력문 => 게임시간 : 10초, 정답개수 : 3개
print(f"게임시간 : {et}초, 정답개수 : {corr_cnt}개")
# 3개이상 정답인 경우 합격 or 불합격
if corr_cnt >= 3:
    print("합격")
else:
    print("불합격") 

    
if corr_cnt >=3:
    print("합격")
else:
    print("불합격")

# db
import oracledb

with oracledb.connect(user="python_user",password="54321",dsn="localhost/xe") as conn:
    with conn.cursor() as cursor:
        
        # record_id : 자동증가 컬럼
        try:
            sql = """create table records(
            record_id number(10) GENERATED BY DEFAULT AS IDENTITY primary key, 
            corr_cnt number,
            record varchar2(20),
            regdate varchar2(30)
            )
            """
        # 실제 오라클database에서 오류가 나면 해당 오류 메세지를 받아오는 작업
            cursor.execute(sql)               
        except oracledb.DatabaseError as e:    
            (error_obj,) = e.args
            if error_obj.code == 955:
                print(error_obj.message)
                pass
            else:
                raise

        # insert 작업(기록 삽입)
        from datetime import datetime
        now = datetime.now()
        nowDateTime=now.strftime("%Y-%m-%d %H:%M:%S")
        sql = "insert into records(corr_cnt,record,regdate) values(:1,:2,:3)"
        cursor.execute(sql,(corr_cnt,et,nowDateTime))
        conn.commit()

print("기록이 저장되었습니다.")